version: "3.9"
services:
  api:
    build:
      dockerfile:  Dockerfile
      context: .
    restart: always
    container_name: six-cities_api
    environment:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mongo:4.2
    restart: always
    container_name: six-cities_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
    ports:
      - 27018:27017
    volumes:
      - six-cities_data:/data/db
  db_ui:
    image: mongo-express:latest
    restart: always
    container_name: six-cities_mongo_express
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@db:27017/
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: password

volumes:
  six-cities_data:
